---
kind: pipeline
type: docker
name: mle-broadcast

steps:
  - name: Build Evidence Project
    image: node:18
    commands:
      - cd mle-broadcast
      - npm i
      - npm run build

  - name: Sync Build Artifacts
    image: drillster/drone-rsync
    settings:
      hosts: ["static-site-rsync"]
      user: root
      port: 22
      source: ./mle-broadcast/build/*
      target: /data/mle-broadcast
      recursive: true
      delete: true
      key:
        from_secret: drone-ssh-key

  - name: Discord Notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
